AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-recor-product-transformer

  Sample SAM Template for sam-recor-product-transformer

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    MemorySize: 128

Resources:
  RecorQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: RecorSqs
      VisibilityTimeout: 120
  LambdaSqsRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
  SampleSQSPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref 'RecorQueue'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: SQS:*
            Effect: "Allow"
            Resource: !GetAtt 'RecorQueue.Arn'
            Principal: '*'
  LambdaFunctionEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 1
      Enabled: true
      EventSourceArn: !GetAtt RecorQueue.Arn
      FunctionName: !GetAtt RecorProductTransformer.Arn
  RecorProductGetter:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: RecorProductGetter/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - arm64
      Environment:
        Variables:
          SQS_QUEUE_URL: !Ref SqsQueueUrl
          WOOCOMMERCE_BASE_URL: !Ref WoocommerceBaseUrl
          WOOCOMMERCE_CONSUMER_KEY: !Ref WoocommerceConsumerKey
          WOOCOMMERCE_CONSUMER_SECRET: !Ref WoocommerceConsumerSecret
          WOOCOMMERCE_IML_COUNTER_PRODUCT_ID: !Ref WoocommerceImlCounterProductId
          IML_BASE_URL: !Ref ImlBaseUrl
          IML_AUTH_TOKEN: !Ref ImlAuthToken
          IML_MAX_ITEMS: !Ref ImlMaxItems
  RecorProductTransformer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: RecorProductTransformer/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - arm64
      Environment:
        Variables:
          WOOCOMMERCE_BASE_URL: !Ref WoocommerceBaseUrl
          WOOCOMMERCE_CONSUMER_KEY: !Ref WoocommerceConsumerKey
          WOOCOMMERCE_CONSUMER_SECRET: !Ref WoocommerceConsumerSecret
          IML_BASE_URL: !Ref ImlBaseUrl
          IML_AUTH_TOKEN: !Ref ImlAuthToken
          IML_MAX_ITEMS: !Ref ImlMaxItems
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ImlItemIdTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ImlCategoryIdTable
      Role: !GetAtt 'LambdaSqsRole.Arn'
  ImlItemIdTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: item_id
        Type: String
      TableName: iml-item-id-table
  ImlCategoryIdTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: category_id
        Type: String
      TableName: iml-category-id-table

Outputs:
  RecorProductGetter:
    Description: "RecorProductGetter Lambda Function ARN"
    Value: !GetAtt RecorProductGetter.Arn
  RecorProductTransformer:
    Description: "RecorProductTransformer Lambda Function ARN"
    Value: !GetAtt RecorProductTransformer.Arn

Parameters:
  WoocommerceBaseUrl:
    Type: String
    Description: "WooCommerce Base URL"
    Default: "localhost"
  WoocommerceConsumerKey:
    Type: String
    Description: "WooCommerce Consumer Key"
    Default: ""
    NoEcho: true
  WoocommerceConsumerSecret:
    Type: String
    Description: "WooCommerce Consumer Secret"
    Default: ""
    NoEcho: true
  WoocommerceImlCounterProductId:
    Type: Number
    Description: "WooCommerce Product ID for IML Last Call Counter"
    Default: 0
  ImlBaseUrl:
    Type: String
    Description: "IML Base Url"
    Default: ""
  ImlAuthToken:
    Type: String
    Description: "IML Auth Token"
    Default: ""
  ImlMaxItems:
    Type: Number
    Description: "Maximum Count of Items to retrieve and publish in the ImlGetItemInfoRequest"
    Default: 100
  SqsQueueUrl:
    Type: String
    Description: "SQS Queue that the ProductGetter publishes and the ProductTransformer consumes"
    Default: ""
